function initIncomeFlowCharts(){
	var areaData = [{
		"x":0,
		"y":0,
		"w":0.19,
		"h":1,
		"bgColor":"#FFFFCC",
		"title":"资源核查",
		"titlePos":"topCenter",
		"dotData":[{
			"cx":0.085,
			"cy":0.20,
			"text":"资源核查",
			"textPos":"top",
			"style":"dot1",
			'id': "ziyuan"
		},{
			"cx":0.085,
			"cy":0.35,
			"text":"客户信息",
			"textPos":"left",
			"style":"dot1",
			'id': "kehu"
		}]
		},{
		"x":0.19,
		"y":0,
		"w":0.19,
		"h":1,
		"bgColor":"#92D050",
		"title":"合同签订",
		"titlePos":"topCenter",
		"dotData":[{
			"cx":0.275,
			"cy":0.20,
			"text":"合同起草",
			"textPos":"top",
			"style":"dot2"
		},{
			"cx":0.275,
			"cy":0.35,
			"text":"合同审批",
			"textPos":"left",
			"style":"dot1"
		},{
			"cx":0.275,
			"cy":0.5,
			"text":"合同扫描",
			"textPos":"left",
			"style":"dot1"
		},{
			"cx":0.275,
			"cy":0.65,
			"text":"合同验证",
			"textPos":"left",
			"style":"dot1"
		},{
			"cx":0.275,
			"cy":0.8,
			"text":"合同注册",
			"textPos":"left",
			"style":"dot1"
		}]
		},{
		"x":0.38,
		"y":0.72,
		"w":0.124,
		"h":0.28,
		"bgColor":"#92D056",
		"title":"",
		"titlePos":"topCenter",
		"dotData":[{
			"cx":0.325,
			"cy":0.8,
			"text":"合同激活",
			"textPos":"bottom",
			"style":"dot1"
		}]
		},{
		"x":0.38,
		"y":0,
		"w":0.124,
		"h":0.72,
		"bgColor":"#FFFF66",
		"title":"线路开通",
		"titlePos":"topCenter",
		"dotData":[{
			"cx":0.442,
			"cy":0.55,
			"text":"开通报竣",
			"textPos":"top",
			"style":"dot1"
		}]},{
		"x":0.504,
		"y":0,
		"w":0.124,
		"h":1,
		"bgColor":"#CCFF99",
		"title":"线路起租",
		"titlePos":"topCenter",
		"dotData":[{
			"cx":0.566,
			"cy":0.8,
			"text":"线路起租",
			"textPos":"bottom",
			"style":"dot1"
		}]},{
		"x":0.628,
		"y":0,
		"w":0.124,
		"h":1,
		"bgColor":"#F0F3F8",
		"title":"线路退租",
		"titlePos":"topCenter",
		"dotData":[{
			"cx":0.69,
			"cy":0.55,
			"text":"线路退组",
			"textPos":"top",
			"style":"dot1"
		}]},{
		"x":0.752,
		"y":0,
		"w":0.124,
		"h":1,
		"bgColor":"#FFCC66",
		"title":"租费结算",
		"titlePos":"topCenter",
		"dotData":[{
			"cx":0.814,
			"cy":0.8,
			"text":"租费结算",
			"textPos":"bottom",
			"style":"dot1"
		}]},{
		"x":0.876,
		"y":0,
		"w":0.124,
		"h":1,
		"bgColor":"#D9D9D9",
		"title":"合同关闭",
		"titlePos":"topCenter",
		"dotData":[{
			"cx":0.938,
			"cy":0.8,
			"text":"合同关闭",
			"textPos":"bottom",
			"style":"dot1"
		}]
	}]
	
	var lineData = [{
		"x1":areaData[0].dotData[0].cx,
		"y1":areaData[0].dotData[0].cy,
		"x2":areaData[0].dotData[1].cx,
		"y2":areaData[0].dotData[1].cy,
		"color":"#66CCFF",
		"width":"4",
		"style":"solid",
		"text":"资源核查-客户信息"
	},{
		"x1":areaData[0].dotData[0].cx,
		"y1":areaData[0].dotData[0].cy,
		"x2":areaData[1].dotData[0].cx,
		"y2":areaData[1].dotData[0].cy,
		"color":"#7F7F7F",
		"width":"4",
		"style":"dotted",
		"text":"资源核查-合同起草"
	},{
		"x1":areaData[1].dotData[0].cx,
		"y1":areaData[1].dotData[0].cy,
		"x2":areaData[1].dotData[4].cx,
		"y2":areaData[1].dotData[4].cy,
		"color":"#66CCFF",
		"width":"4",
		"style":"solid",
		"text":"合同起草-合同注册"
	},{
		"x1":areaData[1].dotData[4].cx,
		"y1":areaData[1].dotData[4].cy,
		"x2":areaData[7].dotData[0].cx,
		"y2":areaData[7].dotData[0].cy,
		"color":"#66CCFF",
		"width":"4",
		"style":"solid",
		"text":"合同注册-合同关闭"
	},
	/*{
		"x1":areaData[3].dotData[0].cx,
		"y1":areaData[3].dotData[0].cy,
		"x2":areaData[4].dotData[0].cx-0.003,
		"y2":areaData[3].dotData[0].cy,
		"color":"#66CCFF",
		"width":"4",
		"style":"solid",
		"text":"开通报竣-线路起租"
	},{
		"x1":areaData[4].dotData[0].cx-0.003,
		"y1":areaData[3].dotData[0].cy,
		"x2":areaData[4].dotData[0].cx-0.003,
		"y2":areaData[4].dotData[0].cy,
		"color":"#66CCFF",
		"width":"4",
		"style":"solid",
		"text":"开通报竣-线路起租"
	},{
		"x1":areaData[4].dotData[0].cx+0.003,
		"y1":areaData[3].dotData[0].cy,
		"x2":areaData[6].dotData[0].cx,
		"y2":areaData[3].dotData[0].cy,
		"color":"#66CCFF",
		"width":"4",
		"style":"solid",
		"text":"合同签订"
	},{
		"x1":areaData[4].dotData[0].cx+0.003,
		"y1":areaData[3].dotData[0].cy,
		"x2":areaData[4].dotData[0].cx+0.003,
		"y2":areaData[4].dotData[0].cy,
		"color":"#66CCFF",
		"width":"4",
		"style":"solid",
		"text":"合同签订"
	},{
		"x1":areaData[6].dotData[0].cx,
		"y1":areaData[3].dotData[0].cy,
		"x2":areaData[6].dotData[0].cx,
		"y2":areaData[6].dotData[0].cy,
		"color":"#66CCFF",
		"width":"4",
		"style":"solid",
		"text":"合同签订"
	}*/
	]
	
	var polyline = [{
		"points":[{
			x:areaData[3].dotData[0].cx,
			y:areaData[3].dotData[0].cy
		},{
			x:(areaData[4].dotData[0].cx-0.003),
			y:areaData[3].dotData[0].cy
		},{
			x:(areaData[4].dotData[0].cx-0.003),
			y:areaData[4].dotData[0].cy
		}],
		"color":"#66CCFF",
		"width":"4",
		"style":"solid",
		"text":"考通报竣-线路起租"
	},{
		"points":[{
			x:(areaData[4].dotData[0].cx+0.003),
			y:areaData[4].dotData[0].cy
		},{
			x:(areaData[4].dotData[0].cx+0.003),
			y:areaData[3].dotData[0].cy
		},{
			x:areaData[6].dotData[0].cx,
			y:areaData[5].dotData[0].cy
		},{
			x:areaData[6].dotData[0].cx,
			y:areaData[6].dotData[0].cy
		}],
		"color":"#66CCFF",
		"width":"4",
		"style":"solid",
		"text":"线路起租-租费结算"
	}];
	
	var triangle = [{
		point:[0,0],
		pos:"bottom",
		dir:"up",
		type:"normal"
	},{
		point:[1,0],
		pos:"left",
		dir:"right",
		type:"small"
	},{
		point:[1,1],
		pos:"up",
		dir:"bottom",
		type:"normal"
	},{
		point:[1,2],
		pos:"up",
		dir:"bottom",
		type:"normal"
	},{
		point:[1,3],
		pos:"up",
		dir:"bottom",
		type:"normal"
	},{
		point:[1,4],
		pos:"up",
		dir:"bottom",
		type:"normal"
	},{
		point:[2,0],
		pos:"left",
		dir:"right",
		type:"normal"
	},{
		point:[4,0],
		pos:"left",
		dir:"right",
		type:"normal"
	},
	{
		point:[4,0],
		pos:"up",
		dir:"bottom",
		type:"normal",
		offsetX:-0.0035
	},
	{
		point:[5,0],
		pos:"left",
		dir:"right",
		type:"normal"
	},{
		point:[6,0],
		pos:"left",
		dir:"right",
		type:"normal"
	},
	{
		point:[6,0],
		pos:"up",
		dir:"bottom",
		type:"normal"
	},
	{
		point:[7,0],
		pos:"left",
		dir:"right",
		type:"normal"
	}];
	var flowData = {
		areaData: areaData,
		lineData: lineData,
		polyline: polyline,
		triangle: triangle
	};
	return flowData;
}